#######################
# Theme Customization #
#######################

title: Merci !                             # used in <title> tag & site header
author: Seungbin Lee                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Hello 911 emergency, there's a handsome guy in my house!
  Oh wait a second, cancel that. I saw myself in the mirror.
slogan: Showtime!                           # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/mercileesb''             # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/mercileesb/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: merci.leesb       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: DELF Feature extraction for Google landmark recognition
    teaser: Easy to extract local feature, works very well.
    url: https://github.com/mercileesb/delf_tensorflow
    role: Leader
    category: Image recognition, Deep feature
  - title: ACM Multimedia'17@Mountain view, Large-Scale Video Classification Challenge
    teaser: LSVC2017 World Rank 8th !
    url: http://lsvc17.azurewebsites.net
    role: Leader
    category: Video classification, Action recognition
  - title: SAMSUNG Electronics C/E Hackathon 2016
    teaser: Detect obstacles, such as pet excrement, using Robot vacuum cleaner.
    url: ""
    role: Leader
    category: Tizen, Embedded computing, Image processing
  - title: SAMSUNG Electronics Tizen 3.0 Tutorials
    teaser: Examples and Wiki docs for newly released tizen version 3.0
    url: https://github.com/mercileesb/tizen-multimedia-apps
    role: Team colleague
    category: Tizen, Embedded computing, Image processing


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
